# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed064a4687807668497c7eea01d5e062a2e6480d5c70561262b2ee1351455e19e9a3c4cb1228583a6e87ed9c6ea8c0e7153bbc1b088149904979116669143802

test:
  secret_key_base: 9dfa4e58b9285d59d2ed7d6244041146785eb7a9f41fcbc715fc9571a39708925c3a66e3a32742e9c9d7b7841b0676d513d2f14073bb044b87aa8698487cd223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
